### ISSUE TITLE
Incompatible with log-core

### ISSUE THREAD

**Issue by sage-sys** [IllidanS4/PawnPlus#46] opened 2021-06-05 13:50 UTC
```
[log-core] fatal signal '11' (SIGSEGV) catched   

[debug] Server crashed due to an unknown error
[debug] Native backtrace:
[debug] #0 f7a05f7f in _Z13GetStackTraceRSt6vectorI10StackFrameSaIS0_EEPv () in plugins/crashdetect.so
[debug] #1 f79fe81d in _ZN11CrashDetect20PrintNativeBacktraceERSoRKN2os7ContextE () in plugins/crashdetect.so
[debug] #2 f79fee48 in _ZN11CrashDetect20PrintNativeBacktraceERKN2os7ContextE () in plugins/crashdetect.so
[debug] #3 f7a005dc in _ZN11CrashDetect7OnCrashERKN2os7ContextE () in plugins/crashdetect.so
[debug] #4 f7a0579f in ?? () in plugins/crashdetect.so
[debug] #5 f7f35570 in __kernel_rt_sigreturn () in linux-gate.so.1
[debug] #6 f7a03d35 in ?? () in plugins/crashdetect.so
[debug] #7 f75f6cda in ?? () in plugins/PawnPlus.so
[debug] #8 f7b60e69 in ?? () in /usr/lib32/libc.so.6
[debug] #9 f7b5dc76 in __nss_database_lookup2 () in /usr/lib32/libc.so.6
[debug] #10 f7b5ed61 in __nss_services_lookup2 () in /usr/lib32/libc.so.6
[debug] #11 f7b4eb02 in getservbyname_r () in /usr/lib32/libc.so.6
[debug] #12 f7b4e95b in getservbyname () in /usr/lib32/libc.so.6
[debug] #13 f712abfc in mysql_server_init () in plugins/mysql.so
[debug] #14 f711fed9 in Load () in plugins/mysql.so
[debug] #15 080d2742 in ?? () in samp03svr
[debug] #16 080d2afa in ?? () in samp03svr
[debug] #17 080aa0d0 in ?? () in samp03svr
[debug] #18 f7a4fa0d in __libc_start_main () in /usr/lib32/libc.so.6
[debug] #19 0804b4e1 in ?? () in samp03svr
[debug] Registers:
[debug] EAX: 09b7b700 EBX: 09ba6260 ECX: 00000004 EDX: 00000000
[debug] ESI: f7bc55ed EDI: f7bc896b EBP: 09b71fb0 ESP: ff9103f0
[debug] EIP: f7a03d35 EFLAGS: 00010286
[debug] Stack:
[debug] ESP+00000000: f75f7320 09b7b704 f77fd9c0 09b7bf88
[debug] ESP+00000020: f7bc896b f7bc55ed f7806000 f75f6ca9
[debug] ESP+00000040: 00000000 07b8bf53 f75f6c79 f7c1fe1c
[debug] ESP+00000060: f7bc896b f7bc55ed 63736e2f 6f732f64
[debug] ESP+00000080: ff91049c f7bc896b 01000000 00000000
[debug] ESP+000000a0: 00000000 00000000 00000000 00000184
[debug] ESP+000000c0: 00000000 60b95072 33a4ccb3 00000801
[debug] ESP+000000e0: 00000011 00000000 00000000 00000000
[debug] ESP+00000100: 00001000 00000008 00000000 60b95102
[debug] ESP+00000120: 07b8bf53 00000002 00000000 00000000
[debug] ESP+00000140: 00000000 00000000 00000000 00000000
[debug] ESP+00000160: 00000000 00000000 00000000 00000000
[debug] ESP+00000180: 00000000 00000000 00000001 53420e00
[debug] ESP+000001a0: f7c1fe1c f7bc88d5 0000000c f7b5dc76
[debug] ESP+000001c0: f70d15fe f7f42aad f70c6b38 f7c1fe1c
[debug] ESP+000001e0: f7bc88d5 00000000 00000000 f7c2377c
[debug] ESP+00000200: 00000400 f7198ff4 f7b5ed2d f7c1fe1c
[debug] ESP+00000220: ff910654 f7bc82f3 00000000 ff910658
[debug] ESP+00000240: 09b7d910 0000006e f7bc82f3 ff910658
[debug] ESP+00000260: 00000000 f70d15fe 00000005 53420e00
[debug] ESP+00000280: 00000400 f7198ff4 00000400 f7b4e95b
[debug] ESP+000002a0: 00000400 ff9106b8 00000000 00000000
[debug] ESP+000002c0: f7f4786d f73da48c 00000000 53420e00
[debug] ESP+000002e0: 00000000 f7450a6c ff910748 f712abfc
[debug] ESP+00000300: f73da48c 09b689a0 09b7c000 f711fed9
[debug] ESP+00000320: 0815ac90 f711fea6 0815ac90 080d2742
[debug] ESP+00000340: 00000000 0816330e 09b7c000 09b68705
[debug] ESP+00000360: 09b689a0 ff910770 ff9107d8 080a10af
[debug] ESP+00000380: 67756c70 2f736e69 7173796d 6f732e6c
[debug] ESP+000003a0: 00000000 00000000 00000000 09b6896c
[debug] ESP+000003c0: 09b65d00 09b68980 00000007 00000009
[debug] ESP+000003e0: ff910830 ff910840 ff910978 080a07e6
[debug] Loaded modules:
[debug] 00000000 - 00187f43 samp03svr
[debug] f7f35000 - f7f362ae linux-gate.so.1
[debug] f7f08000 - f7f0b11c /usr/lib32/libdl.so.2
[debug] f7ee6000 - f7f0568d /usr/lib32/libpthread.so.0
[debug] f7d15000 - f7ef32e7 /usr/lib32/libstdc++.so.6
[debug] f7c47000 - f7d12764 /usr/lib32/libm.so.6
[debug] f7c29000 - f7c44364 /usr/lib32/libgcc_s.so.1
[debug] f7a31000 - f7c2e910 /usr/lib32/libc.so.6
[debug] f7f37000 - f7f68913 /lib/ld-linux.so.2
[debug] f79e6000 - f7a2e3d4 plugins/crashdetect.so
[debug] f79b8000 - f79e7aa3 plugins/timerfix.so
[debug] f79ad000 - f79b585f /usr/lib32/librt.so.1
[debug] f78c4000 - f79aec83 plugins/YSF.so
[debug] f780d000 - f78c4cdf plugins/SKY.so
[debug] f7454000 - f78253ca plugins/PawnPlus.so
[debug] f70c3000 - f7458eb2 plugins/mysql.so
[debug] f709f000 - f70c2d32 /home/sage/Server/plugins/../log-core.so
```
Removing PawnPlus fixes the issue...

```
"dependencies": [
	"sampctl/samp-stdlib",
	"Zeex/samp-plugin-crashdetect:v4.20",
	"pawn-lang/YSI-Includes",
	"ziggi/samp-plugin-timerfix:v1.8",
	"IllidanS4/YSF:v2.1",
	"oscar-broman/samp-weapon-config",
	"IllidanS4/PawnPlus:v1.3.2",
	"pBlueG/SA-MP-MySQL:R41-4",
	"AGraber/pawn-plus-mysql",
	"AGraber/samp-async-dialogs"
],
```

**Comment by IllidanS4** [comment] 2021-06-05 14:58
Duplicate of #38.

**Closed by IllidanS4** 2021-06-05 14:58 UTC
